/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucionesRouteImport } from './routes/soluciones'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as IngenieriaRouteImport } from './routes/ingenieria'
import { Route as IndustriasRouteImport } from './routes/industrias'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as CumplimientoRouteImport } from './routes/cumplimiento'
import { Route as ContratistasRouteImport } from './routes/contratistas'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CapacitacionRouteImport } from './routes/capacitacion'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as ServiciosServicioRouteImport } from './routes/servicios.$servicio'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as IngenieriaServicioRouteImport } from './routes/ingenieria.$servicio'
import { Route as EquiposCategoriaRouteImport } from './routes/equipos.$categoria'
import { Route as CapacitacionCursoRouteImport } from './routes/capacitacion.$curso'
import { Route as PortalClientesIndexRouteImport } from './routes/portal.clientes.index'
import { Route as PortalPlantasSlugRouteImport } from './routes/portal.plantas.$slug'
import { Route as PortalClientesSlugRouteImport } from './routes/portal.clientes.$slug'

const SolucionesRoute = SolucionesRouteImport.update({
  id: '/soluciones',
  path: '/soluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const IngenieriaRoute = IngenieriaRouteImport.update({
  id: '/ingenieria',
  path: '/ingenieria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriasRoute = IndustriasRouteImport.update({
  id: '/industrias',
  path: '/industrias',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const CumplimientoRoute = CumplimientoRouteImport.update({
  id: '/cumplimiento',
  path: '/cumplimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratistasRoute = ContratistasRouteImport.update({
  id: '/contratistas',
  path: '/contratistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacitacionRoute = CapacitacionRouteImport.update({
  id: '/capacitacion',
  path: '/capacitacion',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const ServiciosServicioRoute = ServiciosServicioRouteImport.update({
  id: '/$servicio',
  path: '/$servicio',
  getParentRoute: () => ServiciosRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const IngenieriaServicioRoute = IngenieriaServicioRouteImport.update({
  id: '/$servicio',
  path: '/$servicio',
  getParentRoute: () => IngenieriaRoute,
} as any)
const EquiposCategoriaRoute = EquiposCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => EquiposRoute,
} as any)
const CapacitacionCursoRoute = CapacitacionCursoRouteImport.update({
  id: '/$curso',
  path: '/$curso',
  getParentRoute: () => CapacitacionRoute,
} as any)
const PortalClientesIndexRoute = PortalClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPlantasSlugRoute = PortalPlantasSlugRouteImport.update({
  id: '/plantas/$slug',
  path: '/plantas/$slug',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClientesSlugRoute = PortalClientesSlugRouteImport.update({
  id: '/clientes/$slug',
  path: '/clientes/$slug',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/capacitacion': typeof CapacitacionRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/contratistas': typeof ContratistasRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/facturacion': typeof FacturacionRoute
  '/faq': typeof FaqRoute
  '/industrias': typeof IndustriasRoute
  '/ingenieria': typeof IngenieriaRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/portal': typeof PortalRouteWithChildren
  '/servicios': typeof ServiciosRouteWithChildren
  '/soluciones': typeof SolucionesRoute
  '/capacitacion/$curso': typeof CapacitacionCursoRoute
  '/equipos/$categoria': typeof EquiposCategoriaRoute
  '/ingenieria/$servicio': typeof IngenieriaServicioRoute
  '/portal/login': typeof PortalLoginRoute
  '/servicios/$servicio': typeof ServiciosServicioRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/clientes/$slug': typeof PortalClientesSlugRoute
  '/portal/plantas/$slug': typeof PortalPlantasSlugRoute
  '/portal/clientes/': typeof PortalClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/capacitacion': typeof CapacitacionRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/contratistas': typeof ContratistasRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/facturacion': typeof FacturacionRoute
  '/faq': typeof FaqRoute
  '/industrias': typeof IndustriasRoute
  '/ingenieria': typeof IngenieriaRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/soluciones': typeof SolucionesRoute
  '/capacitacion/$curso': typeof CapacitacionCursoRoute
  '/equipos/$categoria': typeof EquiposCategoriaRoute
  '/ingenieria/$servicio': typeof IngenieriaServicioRoute
  '/portal/login': typeof PortalLoginRoute
  '/servicios/$servicio': typeof ServiciosServicioRoute
  '/portal': typeof PortalIndexRoute
  '/portal/clientes/$slug': typeof PortalClientesSlugRoute
  '/portal/plantas/$slug': typeof PortalPlantasSlugRoute
  '/portal/clientes': typeof PortalClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/capacitacion': typeof CapacitacionRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/contratistas': typeof ContratistasRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/facturacion': typeof FacturacionRoute
  '/faq': typeof FaqRoute
  '/industrias': typeof IndustriasRoute
  '/ingenieria': typeof IngenieriaRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/portal': typeof PortalRouteWithChildren
  '/servicios': typeof ServiciosRouteWithChildren
  '/soluciones': typeof SolucionesRoute
  '/capacitacion/$curso': typeof CapacitacionCursoRoute
  '/equipos/$categoria': typeof EquiposCategoriaRoute
  '/ingenieria/$servicio': typeof IngenieriaServicioRoute
  '/portal/login': typeof PortalLoginRoute
  '/servicios/$servicio': typeof ServiciosServicioRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/clientes/$slug': typeof PortalClientesSlugRoute
  '/portal/plantas/$slug': typeof PortalPlantasSlugRoute
  '/portal/clientes/': typeof PortalClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/capacitacion'
    | '/contacto'
    | '/contratistas'
    | '/cumplimiento'
    | '/equipos'
    | '/facturacion'
    | '/faq'
    | '/industrias'
    | '/ingenieria'
    | '/nosotros'
    | '/portal'
    | '/servicios'
    | '/soluciones'
    | '/capacitacion/$curso'
    | '/equipos/$categoria'
    | '/ingenieria/$servicio'
    | '/portal/login'
    | '/servicios/$servicio'
    | '/portal/'
    | '/portal/clientes/$slug'
    | '/portal/plantas/$slug'
    | '/portal/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/capacitacion'
    | '/contacto'
    | '/contratistas'
    | '/cumplimiento'
    | '/equipos'
    | '/facturacion'
    | '/faq'
    | '/industrias'
    | '/ingenieria'
    | '/nosotros'
    | '/servicios'
    | '/soluciones'
    | '/capacitacion/$curso'
    | '/equipos/$categoria'
    | '/ingenieria/$servicio'
    | '/portal/login'
    | '/servicios/$servicio'
    | '/portal'
    | '/portal/clientes/$slug'
    | '/portal/plantas/$slug'
    | '/portal/clientes'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/capacitacion'
    | '/contacto'
    | '/contratistas'
    | '/cumplimiento'
    | '/equipos'
    | '/facturacion'
    | '/faq'
    | '/industrias'
    | '/ingenieria'
    | '/nosotros'
    | '/portal'
    | '/servicios'
    | '/soluciones'
    | '/capacitacion/$curso'
    | '/equipos/$categoria'
    | '/ingenieria/$servicio'
    | '/portal/login'
    | '/servicios/$servicio'
    | '/portal/'
    | '/portal/clientes/$slug'
    | '/portal/plantas/$slug'
    | '/portal/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  CapacitacionRoute: typeof CapacitacionRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  ContratistasRoute: typeof ContratistasRoute
  CumplimientoRoute: typeof CumplimientoRoute
  EquiposRoute: typeof EquiposRouteWithChildren
  FacturacionRoute: typeof FacturacionRoute
  FaqRoute: typeof FaqRoute
  IndustriasRoute: typeof IndustriasRoute
  IngenieriaRoute: typeof IngenieriaRouteWithChildren
  NosotrosRoute: typeof NosotrosRoute
  PortalRoute: typeof PortalRouteWithChildren
  ServiciosRoute: typeof ServiciosRouteWithChildren
  SolucionesRoute: typeof SolucionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soluciones': {
      id: '/soluciones'
      path: '/soluciones'
      fullPath: '/soluciones'
      preLoaderRoute: typeof SolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingenieria': {
      id: '/ingenieria'
      path: '/ingenieria'
      fullPath: '/ingenieria'
      preLoaderRoute: typeof IngenieriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrias': {
      id: '/industrias'
      path: '/industrias'
      fullPath: '/industrias'
      preLoaderRoute: typeof IndustriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cumplimiento': {
      id: '/cumplimiento'
      path: '/cumplimiento'
      fullPath: '/cumplimiento'
      preLoaderRoute: typeof CumplimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratistas': {
      id: '/contratistas'
      path: '/contratistas'
      fullPath: '/contratistas'
      preLoaderRoute: typeof ContratistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacitacion': {
      id: '/capacitacion'
      path: '/capacitacion'
      fullPath: '/capacitacion'
      preLoaderRoute: typeof CapacitacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/servicios/$servicio': {
      id: '/servicios/$servicio'
      path: '/$servicio'
      fullPath: '/servicios/$servicio'
      preLoaderRoute: typeof ServiciosServicioRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/ingenieria/$servicio': {
      id: '/ingenieria/$servicio'
      path: '/$servicio'
      fullPath: '/ingenieria/$servicio'
      preLoaderRoute: typeof IngenieriaServicioRouteImport
      parentRoute: typeof IngenieriaRoute
    }
    '/equipos/$categoria': {
      id: '/equipos/$categoria'
      path: '/$categoria'
      fullPath: '/equipos/$categoria'
      preLoaderRoute: typeof EquiposCategoriaRouteImport
      parentRoute: typeof EquiposRoute
    }
    '/capacitacion/$curso': {
      id: '/capacitacion/$curso'
      path: '/$curso'
      fullPath: '/capacitacion/$curso'
      preLoaderRoute: typeof CapacitacionCursoRouteImport
      parentRoute: typeof CapacitacionRoute
    }
    '/portal/clientes/': {
      id: '/portal/clientes/'
      path: '/clientes'
      fullPath: '/portal/clientes/'
      preLoaderRoute: typeof PortalClientesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/plantas/$slug': {
      id: '/portal/plantas/$slug'
      path: '/plantas/$slug'
      fullPath: '/portal/plantas/$slug'
      preLoaderRoute: typeof PortalPlantasSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/clientes/$slug': {
      id: '/portal/clientes/$slug'
      path: '/clientes/$slug'
      fullPath: '/portal/clientes/$slug'
      preLoaderRoute: typeof PortalClientesSlugRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface CapacitacionRouteChildren {
  CapacitacionCursoRoute: typeof CapacitacionCursoRoute
}

const CapacitacionRouteChildren: CapacitacionRouteChildren = {
  CapacitacionCursoRoute: CapacitacionCursoRoute,
}

const CapacitacionRouteWithChildren = CapacitacionRoute._addFileChildren(
  CapacitacionRouteChildren,
)

interface EquiposRouteChildren {
  EquiposCategoriaRoute: typeof EquiposCategoriaRoute
}

const EquiposRouteChildren: EquiposRouteChildren = {
  EquiposCategoriaRoute: EquiposCategoriaRoute,
}

const EquiposRouteWithChildren =
  EquiposRoute._addFileChildren(EquiposRouteChildren)

interface IngenieriaRouteChildren {
  IngenieriaServicioRoute: typeof IngenieriaServicioRoute
}

const IngenieriaRouteChildren: IngenieriaRouteChildren = {
  IngenieriaServicioRoute: IngenieriaServicioRoute,
}

const IngenieriaRouteWithChildren = IngenieriaRoute._addFileChildren(
  IngenieriaRouteChildren,
)

interface PortalRouteChildren {
  PortalLoginRoute: typeof PortalLoginRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalClientesSlugRoute: typeof PortalClientesSlugRoute
  PortalPlantasSlugRoute: typeof PortalPlantasSlugRoute
  PortalClientesIndexRoute: typeof PortalClientesIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalLoginRoute: PortalLoginRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalClientesSlugRoute: PortalClientesSlugRoute,
  PortalPlantasSlugRoute: PortalPlantasSlugRoute,
  PortalClientesIndexRoute: PortalClientesIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ServiciosRouteChildren {
  ServiciosServicioRoute: typeof ServiciosServicioRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosServicioRoute: ServiciosServicioRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  CapacitacionRoute: CapacitacionRouteWithChildren,
  ContactoRoute: ContactoRoute,
  ContratistasRoute: ContratistasRoute,
  CumplimientoRoute: CumplimientoRoute,
  EquiposRoute: EquiposRouteWithChildren,
  FacturacionRoute: FacturacionRoute,
  FaqRoute: FaqRoute,
  IndustriasRoute: IndustriasRoute,
  IngenieriaRoute: IngenieriaRouteWithChildren,
  NosotrosRoute: NosotrosRoute,
  PortalRoute: PortalRouteWithChildren,
  ServiciosRoute: ServiciosRouteWithChildren,
  SolucionesRoute: SolucionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
