/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolucionesRouteImport } from './routes/soluciones'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as IngenieriaRouteImport } from './routes/ingenieria'
import { Route as IndustriasRouteImport } from './routes/industrias'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as EquiposRouteImport } from './routes/equipos'
import { Route as CumplimientoRouteImport } from './routes/cumplimiento'
import { Route as ContratistasRouteImport } from './routes/contratistas'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CapacitacionRouteImport } from './routes/capacitacion'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvisoDePrivacidadRouteImport } from './routes/aviso-de-privacidad'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServiciosServicioRouteImport } from './routes/servicios.$servicio'
import { Route as PortalSolicitudesRouteImport } from './routes/portal.solicitudes'
import { Route as PortalSistemasRouteImport } from './routes/portal.sistemas'
import { Route as PortalPersonalRouteImport } from './routes/portal.personal'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalFacturacionRouteImport } from './routes/portal.facturacion'
import { Route as PortalDocumentosRouteImport } from './routes/portal.documentos'
import { Route as PortalConstanciasRouteImport } from './routes/portal.constancias'
import { Route as PortalCertificacionesRouteImport } from './routes/portal.certificaciones'
import { Route as PortalCalendarioRouteImport } from './routes/portal.calendario'
import { Route as PortalBibliotecaRouteImport } from './routes/portal.biblioteca'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'
import { Route as IngenieriaServicioRouteImport } from './routes/ingenieria.$servicio'
import { Route as EquiposCategoriaRouteImport } from './routes/equipos.$categoria'
import { Route as CapacitacionCursoRouteImport } from './routes/capacitacion.$curso'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as PortalProyectosIndexRouteImport } from './routes/portal.proyectos.index'
import { Route as PortalClientesIndexRouteImport } from './routes/portal.clientes.index'
import { Route as PortalProyectosIdRouteImport } from './routes/portal.proyectos.$id'
import { Route as PortalPlantasSlugRouteImport } from './routes/portal.plantas.$slug'
import { Route as PortalClientesSlugRouteImport } from './routes/portal.clientes.$slug'

const SolucionesRoute = SolucionesRouteImport.update({
  id: '/soluciones',
  path: '/soluciones',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const IngenieriaRoute = IngenieriaRouteImport.update({
  id: '/ingenieria',
  path: '/ingenieria',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriasRoute = IndustriasRouteImport.update({
  id: '/industrias',
  path: '/industrias',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const EquiposRoute = EquiposRouteImport.update({
  id: '/equipos',
  path: '/equipos',
  getParentRoute: () => rootRouteImport,
} as any)
const CumplimientoRoute = CumplimientoRouteImport.update({
  id: '/cumplimiento',
  path: '/cumplimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratistasRoute = ContratistasRouteImport.update({
  id: '/contratistas',
  path: '/contratistas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacitacionRoute = CapacitacionRouteImport.update({
  id: '/capacitacion',
  path: '/capacitacion',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoDePrivacidadRoute = AvisoDePrivacidadRouteImport.update({
  id: '/aviso-de-privacidad',
  path: '/aviso-de-privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServiciosServicioRoute = ServiciosServicioRouteImport.update({
  id: '/$servicio',
  path: '/$servicio',
  getParentRoute: () => ServiciosRoute,
} as any)
const PortalSolicitudesRoute = PortalSolicitudesRouteImport.update({
  id: '/solicitudes',
  path: '/solicitudes',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSistemasRoute = PortalSistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPersonalRoute = PortalPersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => PortalRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFacturacionRoute = PortalFacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentosRoute = PortalDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => PortalRoute,
} as any)
const PortalConstanciasRoute = PortalConstanciasRouteImport.update({
  id: '/constancias',
  path: '/constancias',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCertificacionesRoute = PortalCertificacionesRouteImport.update({
  id: '/certificaciones',
  path: '/certificaciones',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCalendarioRoute = PortalCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => PortalRoute,
} as any)
const PortalBibliotecaRoute = PortalBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const IngenieriaServicioRoute = IngenieriaServicioRouteImport.update({
  id: '/$servicio',
  path: '/$servicio',
  getParentRoute: () => IngenieriaRoute,
} as any)
const EquiposCategoriaRoute = EquiposCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => EquiposRoute,
} as any)
const CapacitacionCursoRoute = CapacitacionCursoRouteImport.update({
  id: '/$curso',
  path: '/$curso',
  getParentRoute: () => CapacitacionRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const PortalProyectosIndexRoute = PortalProyectosIndexRouteImport.update({
  id: '/proyectos/',
  path: '/proyectos/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClientesIndexRoute = PortalClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProyectosIdRoute = PortalProyectosIdRouteImport.update({
  id: '/proyectos/$id',
  path: '/proyectos/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPlantasSlugRoute = PortalPlantasSlugRouteImport.update({
  id: '/plantas/$slug',
  path: '/plantas/$slug',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClientesSlugRoute = PortalClientesSlugRouteImport.update({
  id: '/clientes/$slug',
  path: '/clientes/$slug',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/blog': typeof BlogRouteWithChildren
  '/capacitacion': typeof CapacitacionRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/contratistas': typeof ContratistasRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/facturacion': typeof FacturacionRoute
  '/faq': typeof FaqRoute
  '/industrias': typeof IndustriasRoute
  '/ingenieria': typeof IngenieriaRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/portal': typeof PortalRouteWithChildren
  '/servicios': typeof ServiciosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/capacitacion/$curso': typeof CapacitacionCursoRoute
  '/equipos/$categoria': typeof EquiposCategoriaRoute
  '/ingenieria/$servicio': typeof IngenieriaServicioRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/biblioteca': typeof PortalBibliotecaRoute
  '/portal/calendario': typeof PortalCalendarioRoute
  '/portal/certificaciones': typeof PortalCertificacionesRoute
  '/portal/constancias': typeof PortalConstanciasRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/facturacion': typeof PortalFacturacionRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/personal': typeof PortalPersonalRoute
  '/portal/sistemas': typeof PortalSistemasRoute
  '/portal/solicitudes': typeof PortalSolicitudesRoute
  '/servicios/$servicio': typeof ServiciosServicioRoute
  '/blog/': typeof BlogIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/clientes/$slug': typeof PortalClientesSlugRoute
  '/portal/plantas/$slug': typeof PortalPlantasSlugRoute
  '/portal/proyectos/$id': typeof PortalProyectosIdRoute
  '/portal/clientes/': typeof PortalClientesIndexRoute
  '/portal/proyectos/': typeof PortalProyectosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/capacitacion': typeof CapacitacionRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/contratistas': typeof ContratistasRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/facturacion': typeof FacturacionRoute
  '/faq': typeof FaqRoute
  '/industrias': typeof IndustriasRoute
  '/ingenieria': typeof IngenieriaRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/servicios': typeof ServiciosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/capacitacion/$curso': typeof CapacitacionCursoRoute
  '/equipos/$categoria': typeof EquiposCategoriaRoute
  '/ingenieria/$servicio': typeof IngenieriaServicioRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/biblioteca': typeof PortalBibliotecaRoute
  '/portal/calendario': typeof PortalCalendarioRoute
  '/portal/certificaciones': typeof PortalCertificacionesRoute
  '/portal/constancias': typeof PortalConstanciasRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/facturacion': typeof PortalFacturacionRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/personal': typeof PortalPersonalRoute
  '/portal/sistemas': typeof PortalSistemasRoute
  '/portal/solicitudes': typeof PortalSolicitudesRoute
  '/servicios/$servicio': typeof ServiciosServicioRoute
  '/blog': typeof BlogIndexRoute
  '/portal': typeof PortalIndexRoute
  '/portal/clientes/$slug': typeof PortalClientesSlugRoute
  '/portal/plantas/$slug': typeof PortalPlantasSlugRoute
  '/portal/proyectos/$id': typeof PortalProyectosIdRoute
  '/portal/clientes': typeof PortalClientesIndexRoute
  '/portal/proyectos': typeof PortalProyectosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aviso-de-privacidad': typeof AvisoDePrivacidadRoute
  '/blog': typeof BlogRouteWithChildren
  '/capacitacion': typeof CapacitacionRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/contratistas': typeof ContratistasRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/equipos': typeof EquiposRouteWithChildren
  '/facturacion': typeof FacturacionRoute
  '/faq': typeof FaqRoute
  '/industrias': typeof IndustriasRoute
  '/ingenieria': typeof IngenieriaRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/portal': typeof PortalRouteWithChildren
  '/servicios': typeof ServiciosRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/soluciones': typeof SolucionesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/capacitacion/$curso': typeof CapacitacionCursoRoute
  '/equipos/$categoria': typeof EquiposCategoriaRoute
  '/ingenieria/$servicio': typeof IngenieriaServicioRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/biblioteca': typeof PortalBibliotecaRoute
  '/portal/calendario': typeof PortalCalendarioRoute
  '/portal/certificaciones': typeof PortalCertificacionesRoute
  '/portal/constancias': typeof PortalConstanciasRoute
  '/portal/documentos': typeof PortalDocumentosRoute
  '/portal/facturacion': typeof PortalFacturacionRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/personal': typeof PortalPersonalRoute
  '/portal/sistemas': typeof PortalSistemasRoute
  '/portal/solicitudes': typeof PortalSolicitudesRoute
  '/servicios/$servicio': typeof ServiciosServicioRoute
  '/blog/': typeof BlogIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/portal/clientes/$slug': typeof PortalClientesSlugRoute
  '/portal/plantas/$slug': typeof PortalPlantasSlugRoute
  '/portal/proyectos/$id': typeof PortalProyectosIdRoute
  '/portal/clientes/': typeof PortalClientesIndexRoute
  '/portal/proyectos/': typeof PortalProyectosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aviso-de-privacidad'
    | '/blog'
    | '/capacitacion'
    | '/contacto'
    | '/contratistas'
    | '/cumplimiento'
    | '/equipos'
    | '/facturacion'
    | '/faq'
    | '/industrias'
    | '/ingenieria'
    | '/nosotros'
    | '/portal'
    | '/servicios'
    | '/sitemap.xml'
    | '/soluciones'
    | '/blog/$slug'
    | '/capacitacion/$curso'
    | '/equipos/$categoria'
    | '/ingenieria/$servicio'
    | '/portal/admin'
    | '/portal/biblioteca'
    | '/portal/calendario'
    | '/portal/certificaciones'
    | '/portal/constancias'
    | '/portal/documentos'
    | '/portal/facturacion'
    | '/portal/login'
    | '/portal/personal'
    | '/portal/sistemas'
    | '/portal/solicitudes'
    | '/servicios/$servicio'
    | '/blog/'
    | '/portal/'
    | '/portal/clientes/$slug'
    | '/portal/plantas/$slug'
    | '/portal/proyectos/$id'
    | '/portal/clientes/'
    | '/portal/proyectos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aviso-de-privacidad'
    | '/capacitacion'
    | '/contacto'
    | '/contratistas'
    | '/cumplimiento'
    | '/equipos'
    | '/facturacion'
    | '/faq'
    | '/industrias'
    | '/ingenieria'
    | '/nosotros'
    | '/servicios'
    | '/sitemap.xml'
    | '/soluciones'
    | '/blog/$slug'
    | '/capacitacion/$curso'
    | '/equipos/$categoria'
    | '/ingenieria/$servicio'
    | '/portal/admin'
    | '/portal/biblioteca'
    | '/portal/calendario'
    | '/portal/certificaciones'
    | '/portal/constancias'
    | '/portal/documentos'
    | '/portal/facturacion'
    | '/portal/login'
    | '/portal/personal'
    | '/portal/sistemas'
    | '/portal/solicitudes'
    | '/servicios/$servicio'
    | '/blog'
    | '/portal'
    | '/portal/clientes/$slug'
    | '/portal/plantas/$slug'
    | '/portal/proyectos/$id'
    | '/portal/clientes'
    | '/portal/proyectos'
  id:
    | '__root__'
    | '/'
    | '/aviso-de-privacidad'
    | '/blog'
    | '/capacitacion'
    | '/contacto'
    | '/contratistas'
    | '/cumplimiento'
    | '/equipos'
    | '/facturacion'
    | '/faq'
    | '/industrias'
    | '/ingenieria'
    | '/nosotros'
    | '/portal'
    | '/servicios'
    | '/sitemap.xml'
    | '/soluciones'
    | '/blog/$slug'
    | '/capacitacion/$curso'
    | '/equipos/$categoria'
    | '/ingenieria/$servicio'
    | '/portal/admin'
    | '/portal/biblioteca'
    | '/portal/calendario'
    | '/portal/certificaciones'
    | '/portal/constancias'
    | '/portal/documentos'
    | '/portal/facturacion'
    | '/portal/login'
    | '/portal/personal'
    | '/portal/sistemas'
    | '/portal/solicitudes'
    | '/servicios/$servicio'
    | '/blog/'
    | '/portal/'
    | '/portal/clientes/$slug'
    | '/portal/plantas/$slug'
    | '/portal/proyectos/$id'
    | '/portal/clientes/'
    | '/portal/proyectos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AvisoDePrivacidadRoute: typeof AvisoDePrivacidadRoute
  BlogRoute: typeof BlogRouteWithChildren
  CapacitacionRoute: typeof CapacitacionRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  ContratistasRoute: typeof ContratistasRoute
  CumplimientoRoute: typeof CumplimientoRoute
  EquiposRoute: typeof EquiposRouteWithChildren
  FacturacionRoute: typeof FacturacionRoute
  FaqRoute: typeof FaqRoute
  IndustriasRoute: typeof IndustriasRoute
  IngenieriaRoute: typeof IngenieriaRouteWithChildren
  NosotrosRoute: typeof NosotrosRoute
  PortalRoute: typeof PortalRouteWithChildren
  ServiciosRoute: typeof ServiciosRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolucionesRoute: typeof SolucionesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/soluciones': {
      id: '/soluciones'
      path: '/soluciones'
      fullPath: '/soluciones'
      preLoaderRoute: typeof SolucionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingenieria': {
      id: '/ingenieria'
      path: '/ingenieria'
      fullPath: '/ingenieria'
      preLoaderRoute: typeof IngenieriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industrias': {
      id: '/industrias'
      path: '/industrias'
      fullPath: '/industrias'
      preLoaderRoute: typeof IndustriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipos': {
      id: '/equipos'
      path: '/equipos'
      fullPath: '/equipos'
      preLoaderRoute: typeof EquiposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cumplimiento': {
      id: '/cumplimiento'
      path: '/cumplimiento'
      fullPath: '/cumplimiento'
      preLoaderRoute: typeof CumplimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratistas': {
      id: '/contratistas'
      path: '/contratistas'
      fullPath: '/contratistas'
      preLoaderRoute: typeof ContratistasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacitacion': {
      id: '/capacitacion'
      path: '/capacitacion'
      fullPath: '/capacitacion'
      preLoaderRoute: typeof CapacitacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-de-privacidad': {
      id: '/aviso-de-privacidad'
      path: '/aviso-de-privacidad'
      fullPath: '/aviso-de-privacidad'
      preLoaderRoute: typeof AvisoDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/servicios/$servicio': {
      id: '/servicios/$servicio'
      path: '/$servicio'
      fullPath: '/servicios/$servicio'
      preLoaderRoute: typeof ServiciosServicioRouteImport
      parentRoute: typeof ServiciosRoute
    }
    '/portal/solicitudes': {
      id: '/portal/solicitudes'
      path: '/solicitudes'
      fullPath: '/portal/solicitudes'
      preLoaderRoute: typeof PortalSolicitudesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/sistemas': {
      id: '/portal/sistemas'
      path: '/sistemas'
      fullPath: '/portal/sistemas'
      preLoaderRoute: typeof PortalSistemasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/personal': {
      id: '/portal/personal'
      path: '/personal'
      fullPath: '/portal/personal'
      preLoaderRoute: typeof PortalPersonalRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/facturacion': {
      id: '/portal/facturacion'
      path: '/facturacion'
      fullPath: '/portal/facturacion'
      preLoaderRoute: typeof PortalFacturacionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documentos': {
      id: '/portal/documentos'
      path: '/documentos'
      fullPath: '/portal/documentos'
      preLoaderRoute: typeof PortalDocumentosRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/constancias': {
      id: '/portal/constancias'
      path: '/constancias'
      fullPath: '/portal/constancias'
      preLoaderRoute: typeof PortalConstanciasRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/certificaciones': {
      id: '/portal/certificaciones'
      path: '/certificaciones'
      fullPath: '/portal/certificaciones'
      preLoaderRoute: typeof PortalCertificacionesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/calendario': {
      id: '/portal/calendario'
      path: '/calendario'
      fullPath: '/portal/calendario'
      preLoaderRoute: typeof PortalCalendarioRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/biblioteca': {
      id: '/portal/biblioteca'
      path: '/biblioteca'
      fullPath: '/portal/biblioteca'
      preLoaderRoute: typeof PortalBibliotecaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/ingenieria/$servicio': {
      id: '/ingenieria/$servicio'
      path: '/$servicio'
      fullPath: '/ingenieria/$servicio'
      preLoaderRoute: typeof IngenieriaServicioRouteImport
      parentRoute: typeof IngenieriaRoute
    }
    '/equipos/$categoria': {
      id: '/equipos/$categoria'
      path: '/$categoria'
      fullPath: '/equipos/$categoria'
      preLoaderRoute: typeof EquiposCategoriaRouteImport
      parentRoute: typeof EquiposRoute
    }
    '/capacitacion/$curso': {
      id: '/capacitacion/$curso'
      path: '/$curso'
      fullPath: '/capacitacion/$curso'
      preLoaderRoute: typeof CapacitacionCursoRouteImport
      parentRoute: typeof CapacitacionRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/portal/proyectos/': {
      id: '/portal/proyectos/'
      path: '/proyectos'
      fullPath: '/portal/proyectos/'
      preLoaderRoute: typeof PortalProyectosIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/clientes/': {
      id: '/portal/clientes/'
      path: '/clientes'
      fullPath: '/portal/clientes/'
      preLoaderRoute: typeof PortalClientesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/proyectos/$id': {
      id: '/portal/proyectos/$id'
      path: '/proyectos/$id'
      fullPath: '/portal/proyectos/$id'
      preLoaderRoute: typeof PortalProyectosIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/plantas/$slug': {
      id: '/portal/plantas/$slug'
      path: '/plantas/$slug'
      fullPath: '/portal/plantas/$slug'
      preLoaderRoute: typeof PortalPlantasSlugRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/clientes/$slug': {
      id: '/portal/clientes/$slug'
      path: '/clientes/$slug'
      fullPath: '/portal/clientes/$slug'
      preLoaderRoute: typeof PortalClientesSlugRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CapacitacionRouteChildren {
  CapacitacionCursoRoute: typeof CapacitacionCursoRoute
}

const CapacitacionRouteChildren: CapacitacionRouteChildren = {
  CapacitacionCursoRoute: CapacitacionCursoRoute,
}

const CapacitacionRouteWithChildren = CapacitacionRoute._addFileChildren(
  CapacitacionRouteChildren,
)

interface EquiposRouteChildren {
  EquiposCategoriaRoute: typeof EquiposCategoriaRoute
}

const EquiposRouteChildren: EquiposRouteChildren = {
  EquiposCategoriaRoute: EquiposCategoriaRoute,
}

const EquiposRouteWithChildren =
  EquiposRoute._addFileChildren(EquiposRouteChildren)

interface IngenieriaRouteChildren {
  IngenieriaServicioRoute: typeof IngenieriaServicioRoute
}

const IngenieriaRouteChildren: IngenieriaRouteChildren = {
  IngenieriaServicioRoute: IngenieriaServicioRoute,
}

const IngenieriaRouteWithChildren = IngenieriaRoute._addFileChildren(
  IngenieriaRouteChildren,
)

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalBibliotecaRoute: typeof PortalBibliotecaRoute
  PortalCalendarioRoute: typeof PortalCalendarioRoute
  PortalCertificacionesRoute: typeof PortalCertificacionesRoute
  PortalConstanciasRoute: typeof PortalConstanciasRoute
  PortalDocumentosRoute: typeof PortalDocumentosRoute
  PortalFacturacionRoute: typeof PortalFacturacionRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalPersonalRoute: typeof PortalPersonalRoute
  PortalSistemasRoute: typeof PortalSistemasRoute
  PortalSolicitudesRoute: typeof PortalSolicitudesRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalClientesSlugRoute: typeof PortalClientesSlugRoute
  PortalPlantasSlugRoute: typeof PortalPlantasSlugRoute
  PortalProyectosIdRoute: typeof PortalProyectosIdRoute
  PortalClientesIndexRoute: typeof PortalClientesIndexRoute
  PortalProyectosIndexRoute: typeof PortalProyectosIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalBibliotecaRoute: PortalBibliotecaRoute,
  PortalCalendarioRoute: PortalCalendarioRoute,
  PortalCertificacionesRoute: PortalCertificacionesRoute,
  PortalConstanciasRoute: PortalConstanciasRoute,
  PortalDocumentosRoute: PortalDocumentosRoute,
  PortalFacturacionRoute: PortalFacturacionRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalPersonalRoute: PortalPersonalRoute,
  PortalSistemasRoute: PortalSistemasRoute,
  PortalSolicitudesRoute: PortalSolicitudesRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalClientesSlugRoute: PortalClientesSlugRoute,
  PortalPlantasSlugRoute: PortalPlantasSlugRoute,
  PortalProyectosIdRoute: PortalProyectosIdRoute,
  PortalClientesIndexRoute: PortalClientesIndexRoute,
  PortalProyectosIndexRoute: PortalProyectosIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ServiciosRouteChildren {
  ServiciosServicioRoute: typeof ServiciosServicioRoute
}

const ServiciosRouteChildren: ServiciosRouteChildren = {
  ServiciosServicioRoute: ServiciosServicioRoute,
}

const ServiciosRouteWithChildren = ServiciosRoute._addFileChildren(
  ServiciosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AvisoDePrivacidadRoute: AvisoDePrivacidadRoute,
  BlogRoute: BlogRouteWithChildren,
  CapacitacionRoute: CapacitacionRouteWithChildren,
  ContactoRoute: ContactoRoute,
  ContratistasRoute: ContratistasRoute,
  CumplimientoRoute: CumplimientoRoute,
  EquiposRoute: EquiposRouteWithChildren,
  FacturacionRoute: FacturacionRoute,
  FaqRoute: FaqRoute,
  IndustriasRoute: IndustriasRoute,
  IngenieriaRoute: IngenieriaRouteWithChildren,
  NosotrosRoute: NosotrosRoute,
  PortalRoute: PortalRouteWithChildren,
  ServiciosRoute: ServiciosRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolucionesRoute: SolucionesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
