// Auto-generated by /tmp/extract.ts — real images scraped from kg-safety.com
// Do not edit by hand; re-run extraction to refresh.
export const REAL_ASSETS: Record<string, string[]> = {
  "cursos-alturas": [
    "cursos-alturas/51b6c30b52.jpg"
  ],
  "cursos-loto": [
    "cursos-loto/4c2731af84.png"
  ],
  "consultoria": [
    "consultoria/88dbd2663f.png"
  ]
} as const;
export type RealBucket = keyof typeof REAL_ASSETS;
