// Auto-generated by /tmp/extract-live.ts — real images from kg-safety.com
export const REAL_ASSETS: Record<string, string[]> = {
  "logo": [
    "logo/f32e105398.png",
    "logo/d182645233.png",
    "logo/4c2731af84.png"
  ],
  "iconos-servicios": [
    "iconos-servicios/534f9874f9.png",
    "iconos-servicios/f4873a963a.png",
    "iconos-servicios/cec8ffc0fa.png",
    "iconos-servicios/8ed2d9624e.png",
    "iconos-servicios/5a6946ee87.png",
    "iconos-servicios/ccd99ab804.png",
    "iconos-servicios/33d4ecac5b.png",
    "iconos-servicios/dad8a7b72a.png"
  ],
  "logos-clientes": [
    "logos-clientes/5d2e6fd0ac.png",
    "logos-clientes/3f25a8254d.png",
    "logos-clientes/7c7cc9ca5f.png",
    "logos-clientes/fd5716406a.png",
    "logos-clientes/0897632798.png",
    "logos-clientes/01870947f2.png",
    "logos-clientes/6ce47a420f.png",
    "logos-clientes/2092f918dc.png",
    "logos-clientes/0babc8c2ab.png"
  ],
  "consultoria": [
    "consultoria/9210aa1b1e.png",
    "consultoria/58f91a55af.png",
    "consultoria/c61c4aa9e3.png",
    "consultoria/4624f93bd2.png",
    "consultoria/4d84386a9a.png",
    "consultoria/9f4103082f.png",
    "consultoria/9d2adb3d89.png",
    "consultoria/3e4cd13c9b.png",
    "consultoria/3430e78c8b.jpg",
    "consultoria/06062a151b.png",
    "consultoria/a28b54eb06.png",
    "consultoria/9a686f54e3.png",
    "consultoria/961025f8b3.png",
    "consultoria/cb8ff10a48.png",
    "consultoria/dcc16f2ccf.png",
    "consultoria/31299f3221.png",
    "consultoria/2c5c11beed.png",
    "consultoria/5c5b8a8572.jpg"
  ]
};
export type RealBucket = keyof typeof REAL_ASSETS;
